[package]
name = "hypothesis"
version = "0.1.0"
authors = ["Ninjani"]
edition = "2018"

[dependencies]
reqwest = {version="0.10.4", features=["json", "blocking"]}
eyre = "0.4.2"
color-eyre = "0.3.2"
chrono = {version = "0.4.11", features = ["serde"]}
serde = {version = "1.0.110", features = ["derive"]}
serde_json = "1.0.53"
dotenv = "0.15.0"